[theme]
base = "light"
primaryColor = "#0f62fe"
backgroundColor = "#f4f4f4"
secondaryBackgroundColor = "#ffffff"
textColor = "#161616"
linkColor = "#0f62fe"
borderColor = "#c6c6c6"
codeBackgroundColor = "#e0e0e0"
codeTextColor = "#161616"
redColor = "#da1e28"
orangeColor = "#ff832b"
yellowColor = "#f1c21b"
greenColor = "#198038"
blueColor = "#0f62fe"
violetColor = "#8a3ffc"
grayColor = "#6f6f6f"
chartCategoricalColors = ["#4589ff", "#009d9a", "#a56eff", "#1192e8", "#24a148", "#ee5396", "#ff832b", "#8d8d8d"]
chartSequentialColors = ["#edf5ff", "#d0e2ff", "#a6c8ff", "#78a9ff", "#4589ff", "#0f62fe", "#0043ce", "#002d9c", "#001d6c", "#001141"]
dataframeBorderColor = "#e0e0e0"
dataframeHeaderBackgroundColor = "#f4f4f4"
font = "'IBM Plex Sans':https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600&display=swap"
headingFont = "'IBM Plex Sans':https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600&display=swap"
codeFont = "'IBM Plex Mono':https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&display=swap"
baseFontSize = 16
baseFontWeight = 400
baseRadius = "none"
buttonRadius = "none"
showWidgetBorder = true
showSidebarBorder = false
linkUnderline = false
headingFontSizes = ["2rem", "1.25rem", "1.125rem", "1rem", "0.875rem", "0.75rem"]
headingFontWeights = [600, 600, 600, 500, 500, 500]

[theme.sidebar]
backgroundColor = "#f4f4f4"
secondaryBackgroundColor = "#e0e0e0"
textColor = "#161616"
borderColor = "#c6c6c6"
primaryColor = "#0f62fe"
